services:
#  app:
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt
#    depends_on:
#      - todos-service
#
#  nginx:
#    image: nginx:latest
#    restart: unless-stopped
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - todos-service

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: hamroh-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hamroh
    ports:
      - "5432:5432"

#  todos-service:
#    image: golang:1.24-alpine
#    command: sh -c "go run ./cmd/todo/migrate/main.go && go run ./cmd/todo/main.go"
#    restart: unless-stopped
#    working_dir: /todo
#    volumes:
#      - ./projects/todo:/todo
#    depends_on:
#      - postgres
